### ISSUE TITLE
为什么我克隆下来用不了，报了一大堆错误

### ISSUE THREAD

**Issue by GuanryA5** [Lonezj/hexo-theme-wind#1]

**Comment by voezy** [comment]
@GuanryA5 你好，请问具体是哪些错误呢？可以把错误代码贴上来吗？

**Comment by GuanryA5** [comment]
我的步骤是这样的，我重新来了一遍。 npm install hexo-cli -g , npm init blog , cd blog ,npm install . 修改站点文件 them 主题为 wind   ，在 them 目录下 clone 你的项目 改名为wind  . 然后hexo g ,hexo s 。 页面加载不出来

**Comment by GuanryA5** [comment]
Unhandled rejection TypeError: C:\Users\Gruiy\Blog\themes\wind\layout\post.ejs:79
    77|
    78| <% if(page.comments) { %>
 >> 79|     <% if(page.comments && theme.comment.use) { %>
    80|     
    81|     <div class="post-comment-wrapper">
    82|         <%- partial('_widget/comment') %>

Cannot read property 'use' of undefined
    at eval (eval at compile (C:\Users\Gruiy\Blog\node_modules\ejs\lib\ejs.js:549:12), <anonymous>:132:42)
    at returnedFn (C:\Users\Gruiy\Blog\node_modules\ejs\lib\ejs.js:580:17)
    at Theme._View.View._compiled (C:\Users\Gruiy\Blog\node_modules\hexo\lib\theme\view.js:127:30)
    at Theme._View.View.View.render (C:\Users\Gruiy\Blog\node_modules\hexo\lib\theme\view.js:29:15)
    at C:\Users\Gruiy\Blog\node_modules\hexo\lib\hexo\index.js:390:25
    at tryCatcher (C:\Users\Gruiy\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at C:\Users\Gruiy\Blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (C:\Users\Gruiy\Blog\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:442:10)
    at resume_ (_stream_readable.js:822:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

Unhandled rejection TypeError: C:\Users\Gruiy\Blog\themes\wind\layout\layout.ejs:4
    2| <html>
    3|     
 >> 4|     <%- partial('_partial/head') %>
    5|     <body>
    6|         <div class="container">
    7|

C:\Users\Gruiy\Blog\themes\wind\layout\_partial\head.ejs:6
    4|     <meta name="author" content="<%= config.author %>">
    5|     <meta name="description" itemprop="description" content="<% if(page.description) { %><%= page.description %><% } else if(page.excerpt){ %><%= strip_html(page.excerpt).replace(/^s*/, '').replace(/s*$/, '') %><% } else if (config.description){ %><%= config.description %><% } %>">
 >> 6|     <meta name="keywords" content="<%= theme.head.keywords %><% if(page.tags && page.tags.each) { page.tags.each(function(tag) { %><%- ',' + tag.name %><% })} %>">
    7|
    8|     
    9|     <% if(page.layout=='post') { %>

Cannot read property 'keywords' of undefined
    at eval (eval at compile (C:\Users\Gruiy\Blog\node_modules\ejs\lib\ejs.js:549:12), <anonymous>:23:37)
    at returnedFn (C:\Users\Gruiy\Blog\node_modules\ejs\lib\ejs.js:580:17)
    at Theme._View.View._compiledSync (C:\Users\Gruiy\Blog\node_modules\hexo\lib\theme\view.js:122:20)
    at Theme._View.View.View.renderSync (C:\Users\Gruiy\Blog\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (C:\Users\Gruiy\Blog\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper [as partial] (C:\Users\Gruiy\Blog\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at compile (C:\Users\Gruiy\Blog\node_modules\ejs\lib\ejs.js:549:12), <anonymous>:11:17)
    at returnedFn (C:\Users\Gruiy\Blog\node_modules\ejs\lib\ejs.js:580:17)
    at Theme._View.View._compiled (C:\Users\Gruiy\Blog\node_modules\hexo\lib\theme\view.js:127:30)
    at Theme._View.View.View.render (C:\Users\Gruiy\Blog\node_modules\hexo\lib\theme\view.js:29:15)
    at C:\Users\Gruiy\Blog\node_modules\hexo\lib\theme\view.js:40:23
    at tryCatcher (C:\Users\Gruiy\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Gruiy\Blog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\Gruiy\Blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\Gruiy\Blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\Gruiy\Blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\Gruiy\Blog\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Gruiy\Blog\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Gruiy\Blog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

Unhandled rejection TypeError: C:\Users\Gruiy\Blog\themes\wind\layout\layout.ejs:4
    2| <html>
    3|     
 >> 4|     <%- partial('_partial/head') %>
    5|     <body>
    6|         <div class="container">
    7|

C:\Users\Gruiy\Blog\themes\wind\layout\_partial\head.ejs:6
    4|     <meta name="author" content="<%= config.author %>">
    5|     <meta name="description" itemprop="description" content="<% if(page.description) { %><%= page.description %><% } else if(page.excerpt){ %><%= strip_html(page.excerpt).replace(/^s*/, '').replace(/s*$/, '') %><% } else if (config.description){ %><%= config.description %><% } %>">
 >> 6|     <meta name="keywords" content="<%= theme.head.keywords %><% if(page.tags && page.tags.each) { page.tags.each(function(tag) { %><%- ',' + tag.name %><% })} %>">
    7|
    8|     
    9|     <% if(page.layout=='post') { %>

Cannot read property 'keywords' of undefined
    at eval (eval at compile (C:\Users\Gruiy\Blog\node_modules\ejs\lib\ejs.js:549:12), <anonymous>:23:37)
    at returnedFn (C:\Users\Gruiy\Blog\node_modules\ejs\lib\ejs.js:580:17)
    at Theme._View.View._compiledSync (C:\Users\Gruiy\Blog\node_modules\hexo\lib\theme\view.js:122:20)
    at Theme._View.View.View.renderSync (C:\Users\Gruiy\Blog\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (C:\Users\Gruiy\Blog\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper [as partial] (C:\Users\Gruiy\Blog\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at compile (C:\Users\Gruiy\Blog\node_modules\ejs\lib\ejs.js:549:12), <anonymous>:11:17)
    at returnedFn (C:\Users\Gruiy\Blog\node_modules\ejs\lib\ejs.js:580:17)
    at Theme._View.View._compiled (C:\Users\Gruiy\Blog\node_modules\hexo\lib\theme\view.js:127:30)
    at Theme._View.View.View.render (C:\Users\Gruiy\Blog\node_modules\hexo\lib\theme\view.js:29:15)
    at C:\Users\Gruiy\Blog\node_modules\hexo\lib\theme\view.js:40:23
    at tryCatcher (C:\Users\Gruiy\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Gruiy\Blog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\Gruiy\Blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\Gruiy\Blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\Gruiy\Blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\Gruiy\Blog\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Gruiy\Blog\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Gruiy\Blog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

Unhandled rejection TypeError: C:\Users\Gruiy\Blog\themes\wind\layout\layout.ejs:4
    2| <html>
    3|     
 >> 4|     <%- partial('_partial/head') %>
    5|     <body>
    6|         <div class="container">
    7|

C:\Users\Gruiy\Blog\themes\wind\layout\_partial\head.ejs:6
    4|     <meta name="author" content="<%= config.author %>">
    5|     <meta name="description" itemprop="description" content="<% if(page.description) { %><%= page.description %><% } else if(page.excerpt){ %><%= strip_html(page.excerpt).replace(/^s*/, '').replace(/s*$/, '') %><% } else if (config.description){ %><%= config.description %><% } %>">
 >> 6|     <meta name="keywords" content="<%= theme.head.keywords %><% if(page.tags && page.tags.each) { page.tags.each(function(tag) { %><%- ',' + tag.name %><% })} %>">
    7|
    8|     
    9|     <% if(page.layout=='post') { %>

Cannot read property 'keywords' of undefined
    at eval (eval at compile (C:\Users\Gruiy\Blog\node_modules\ejs\lib\ejs.js:549:12), <anonymous>:23:37)
    at returnedFn (C:\Users\Gruiy\Blog\node_modules\ejs\lib\ejs.js:580:17)
    at Theme._View.View._compiledSync (C:\Users\Gruiy\Blog\node_modules\hexo\lib\theme\view.js:122:20)
    at Theme._View.View.View.renderSync (C:\Users\Gruiy\Blog\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (C:\Users\Gruiy\Blog\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper [as partial] (C:\Users\Gruiy\Blog\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at compile (C:\Users\Gruiy\Blog\node_modules\ejs\lib\ejs.js:549:12), <anonymous>:11:17)
    at returnedFn (C:\Users\Gruiy\Blog\node_modules\ejs\lib\ejs.js:580:17)
    at Theme._View.View._compiled (C:\Users\Gruiy\Blog\node_modules\hexo\lib\theme\view.js:127:30)
    at Theme._View.View.View.render (C:\Users\Gruiy\Blog\node_modules\hexo\lib\theme\view.js:29:15)
    at C:\Users\Gruiy\Blog\node_modules\hexo\lib\theme\view.js:40:23
    at tryCatcher (C:\Users\Gruiy\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Gruiy\Blog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\Gruiy\Blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\Gruiy\Blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\Gruiy\Blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\Gruiy\Blog\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Gruiy\Blog\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Gruiy\Blog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

Unhandled rejection TypeError: C:\Users\Gruiy\Blog\themes\wind\layout\layout.ejs:4
    2| <html>
    3|     
 >> 4|     <%- partial('_partial/head') %>
    5|     <body>
    6|         <div class="container">
    7|

C:\Users\Gruiy\Blog\themes\wind\layout\_partial\head.ejs:6
    4|     <meta name="author" content="<%= config.author %>">
    5|     <meta name="description" itemprop="description" content="<% if(page.description) { %><%= page.description %><% } else if(page.excerpt){ %><%= strip_html(page.excerpt).replace(/^s*/, '').replace(/s*$/, '') %><% } else if (config.description){ %><%= config.description %><% } %>">
 >> 6|     <meta name="keywords" content="<%= theme.head.keywords %><% if(page.tags && page.tags.each) { page.tags.each(function(tag) { %><%- ',' + tag.name %><% })} %>">
    7|
    8|     
    9|     <% if(page.layout=='post') { %>

Cannot read property 'keywords' of undefined
    at eval (eval at compile (C:\Users\Gruiy\Blog\node_modules\ejs\lib\ejs.js:549:12), <anonymous>:23:37)
    at returnedFn (C:\Users\Gruiy\Blog\node_modules\ejs\lib\ejs.js:580:17)
    at Theme._View.View._compiledSync (C:\Users\Gruiy\Blog\node_modules\hexo\lib\theme\view.js:122:20)
    at Theme._View.View.View.renderSync (C:\Users\Gruiy\Blog\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (C:\Users\Gruiy\Blog\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper [as partial] (C:\Users\Gruiy\Blog\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at compile (C:\Users\Gruiy\Blog\node_modules\ejs\lib\ejs.js:549:12), <anonymous>:11:17)
    at returnedFn (C:\Users\Gruiy\Blog\node_modules\ejs\lib\ejs.js:580:17)
    at Theme._View.View._compiled (C:\Users\Gruiy\Blog\node_modules\hexo\lib\theme\view.js:127:30)
    at Theme._View.View.View.render (C:\Users\Gruiy\Blog\node_modules\hexo\lib\theme\view.js:29:15)
    at C:\Users\Gruiy\Blog\node_modules\hexo\lib\theme\view.js:40:23
    at tryCatcher (C:\Users\Gruiy\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Gruiy\Blog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\Gruiy\Blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\Gruiy\Blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\Gruiy\Blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\Gruiy\Blog\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Gruiy\Blog\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Gruiy\Blog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

**Comment by GuanryA5** [comment]
@Lonezj

**Comment by voezy** [comment]
@GuanryA5 是不是还没有把wind下面的_config.sample.yml重命名为_config.yml？默认的主题配置文件名要做这样一个修改。
